name: Deploy HerdSmart API to runasp.net
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore Dependencies
        run: dotnet restore ./Api/Api.csproj
      - name: Publish Web API
        run: dotnet publish ./Api/Api.csproj --configuration Release --output ./publish

      - name: Take app offline
        run: |
          echo "App is being updated, please wait..." > app_offline.htm
          curl -T app_offline.htm "ftp://${{ secrets.FTP_SERVER }}/wwwroot/app_offline.htm" --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"
          echo "Waiting for IIS to release file locks..."
          sleep 10

      - name: Sync FTP Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: ./wwwroot/

      - name: Bring app back online
        run: |
          curl -Q "-DELE app_offline.htm" "ftp://${{ secrets.FTP_SERVER }}/wwwroot/" --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"